### PR TITLE
Fix error caused by ' within tildes

### PR DESCRIPTION
**Pull request by kirkportas**

### CODE REVIEW

**Comment by bonzaiferroni** [comment]
You get an error from this? Is that a styling error in your IDE?

**Comment by kirkportas** [comment]
I copypasted `Traveler.js` into my codebase, required it in main, and screeps.com was throwing an error on that line. I'll doublecheck this week with a fresh paste from master:Traveler.js and close this if it works.

**Comment by bonzaiferroni** [comment]
Appreciated, let me know how it turns out. There might be something about how template strings are handled that could be causing the issue.

**Comment by bonzaiferroni** [comment]
@kirkportas any word on this? I haven't been able to reproduce it.

**Comment by JLLeitschuh** [comment]
This isn't an issue in typescript. At least not in Webstorm.

**Pull request closed without merging**
